package recipeNo072;

/**
* Custom exception that will be used for throwing errno with
* associated message
*/

public class ErrnoException extends Exception {

  // placeholder for errno generated by system call
  private int errno = 0;

  public ErrnoException(String message, int errno) {

    super(message);
    this.errno = errno;

  }

  public int getErrno() {
    return errno;
  }
  
}
