/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recipeNo032_Main */

#ifndef _Included_recipeNo032_Main
#define _Included_recipeNo032_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     recipeNo032_Main
 * Method:    callmeback
 * Signature: ()V
 */
  JNIEXPORT void JNICALL Java_recipeNo032_Main_callmeback (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
